PORTNAME=	libgdbstub
DISTVERSION=	g20200129
CATEGORIES=	emulators devel

MAINTAINER=	0mp@FreeBSD.org
COMMENT=	Simple freestanding GDB stub library for parsing the GDB serial remote protocol

LICENSE=	MIT
LICENSE_FILE=	${WRKSRC}/LICENSE

USES=		cmake pkgconfig
USE_GITHUB=	yes
GH_ACCOUNT=	AlexanderEichner
GH_TAGNAME=	ae647b4

.include <bsd.port.mk>
